# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d2c0330b1e1d6c3596af0cd1580ce05cdbd9697495568a1c167adf947c600f66e6418bda3daedb85e7baa20f32d6916b15aa9998669282eabd2fd414cabafb

test:
  secret_key_base: 0176d06531c98d6b8c0935e7984a275f46659529c0b48191cfd46e985fc8b610c05cb463146bfe90f9beee2c6e8cef4e0679fa795b9036de4aabd2066cc0aee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
